export const metadata = {
  title: 'memo',
  description: 'Generated by Next.js',
}

export default function RegisterLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <main>
        {children}
      </main>
    </>
  )
}
